const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');
const logger = require('../config/logger');

class ReportGenerator {
  constructor() {
    this.reportsDir = path.join(__dirname, '../../reports');
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  // Generate PDF report
  async generatePDF(reportData, options = {}) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ 
          margin: 50,
          size: options.size || 'A4',
          layout: options.layout || 'portrait'
        });

        const filename = `report-${Date.now()}.pdf`;
        const filepath = path.join(this.reportsDir, filename);
        const stream = fs.createWriteStream(filepath);

        doc.pipe(stream);

        // Add header
        this.addPDFHeader(doc, options);

        // Add title
        doc.fontSize(20).font('Helvetica-Bold')
          .text(options.title || 'Report', { align: 'center' })
          .moveDown();

        // Add date range
        if (options.startDate && options.endDate) {
          doc.fontSize(10).font('Helvetica')
            .text(`Period: ${new Date(options.startDate).toLocaleDateString()} - ${new Date(options.endDate).toLocaleDateString()}`, { align: 'center' })
            .moveDown();
        }

        // Add summary
        if (reportData.summary) {
          this.addPDFSummary(doc, reportData.summary);
        }

        // Add table
        if (reportData.data && reportData.data.length > 0) {
          this.addPDFTable(doc, reportData.data, options.columns);
        }

        // Add footer
        this.addPDFFooter(doc);

        doc.end();

        stream.on('finish', () => resolve(filepath));
        stream.on('error', reject);
      } catch (error) {
        logger.error('PDF generation error:', error);
        reject(error);
      }
    });
  }

  // Add PDF header
  addPDFHeader(doc, options) {
    doc.fontSize(10).font('Helvetica')
      .text(options.shopName || process.env.SHOP_NAME || 'ElectroStore', 50, 50)
      .text(`Generated: ${new Date().toLocaleString()}`, 50, 65)
      .text(`Generated by: ${options.generatedBy || 'System'}`, 50, 80);
    
    doc.moveDown(4);
  }

  // Add PDF summary
  addPDFSummary(doc, summary) {
    doc.fontSize(12).font('Helvetica-Bold')
      .text('Summary', { underline: true })
      .moveDown(0.5);

    const startY = doc.y;
    let x = 50;
    const colWidth = 150;

    Object.entries(summary).forEach(([key, value], index) => {
      if (index % 3 === 0 && index > 0) {
        x = 50;
        doc.y += 20;
      }

      doc.fontSize(10)
        .font('Helvetica-Bold')
        .text(key.replace(/([A-Z])/g, ' $1').trim() + ':', x, doc.y)
        .font('Helvetica')
        .text(this.formatValue(value), x + 80, doc.y - 12);

      x += colWidth;
    });

    doc.y += 40;
  }

  // Add PDF table
  addPDFTable(doc, data, columns) {
    if (!columns) {
      columns = Object.keys(data[0]).map(key => ({
        header: key.replace(/([A-Z])/g, ' $1').trim(),
        key: key
      }));
    }

    const tableTop = doc.y;
    const colWidth = (doc.page.width - 100) / columns.length;

    // Draw headers
    doc.fontSize(10).font('Helvetica-Bold');
    columns.forEach((col, i) => {
      doc.text(col.header, 50 + (i * colWidth), tableTop);
    });

    // Draw line
    doc.moveTo(50, tableTop + 15)
      .lineTo(doc.page.width - 50, tableTop + 15)
      .stroke();

    // Draw rows
    doc.fontSize(8).font('Helvetica');
    let y = tableTop + 25;

    data.forEach((row, rowIndex) => {
      if (y > doc.page.height - 100) {
        doc.addPage();
        y = 50;
      }

      columns.forEach((col, i) => {
        const value = this.formatValue(row[col.key]);
        doc.text(value, 50 + (i * colWidth), y, { width: colWidth - 10 });
      });

      y += 20;

      // Draw light line between rows
      if (rowIndex < data.length - 1) {
        doc.strokeColor('#ccc')
          .moveTo(50, y - 5)
          .lineTo(doc.page.width - 50, y - 5)
          .stroke();
      }
    });

    doc.strokeColor('#000');
  }

  // Add PDF footer
  addPDFFooter(doc) {
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8)
        .text(
          `Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 50,
          { align: 'center' }
        );
    }
  }

  // Generate Excel report
  async generateExcel(reportData, options = {}) {
    try {
      const workbook = new ExcelJS.Workbook();
      workbook.creator = options.generatedBy || 'System';
      workbook.lastModifiedBy = options.generatedBy || 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      const worksheet = workbook.addWorksheet(options.sheetName || 'Report');

      // Add title
      worksheet.mergeCells('A1', 'F1');
      const titleCell = worksheet.getCell('A1');
      titleCell.value = options.title || 'Report';
      titleCell.font = { size: 16, bold: true };
      titleCell.alignment = { horizontal: 'center' };

      // Add date range
      if (options.startDate && options.endDate) {
        worksheet.mergeCells('A2', 'F2');
        const dateCell = worksheet.getCell('A2');
        dateCell.value = `Period: ${new Date(options.startDate).toLocaleDateString()} - ${new Date(options.endDate).toLocaleDateString()}`;
        dateCell.alignment = { horizontal: 'center' };
      }

      let currentRow = 4;

      // Add summary
      if (reportData.summary) {
        worksheet.getCell(`A${currentRow}`).value = 'Summary';
        worksheet.getCell(`A${currentRow}`).font = { bold: true, size: 12 };
        currentRow++;

        Object.entries(reportData.summary).forEach(([key, value]) => {
          worksheet.getCell(`A${currentRow}`).value = key.replace(/([A-Z])/g, ' $1').trim();
          worksheet.getCell(`B${currentRow}`).value = this.formatValue(value);
          worksheet.getCell(`B${currentRow}`).alignment = { horizontal: 'right' };
          currentRow++;
        });

        currentRow += 2;
      }

      // Add data table
      if (reportData.data && reportData.data.length > 0) {
        const columns = options.columns || Object.keys(reportData.data[0]).map(key => ({
          header: key.replace(/([A-Z])/g, ' $1').trim(),
          key: key,
          width: 15
        }));

        // Add headers
        worksheet.columns = columns.map(col => ({
          header: col.header,
          key: col.key,
          width: col.width || 15
        }));

        // Add rows
        worksheet.addRows(reportData.data);

        // Style headers
        const headerRow = worksheet.getRow(currentRow);
        headerRow.font = { bold: true };
        headerRow.eachCell(cell => {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FF2563EB' }
          };
          cell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
          cell.alignment = { horizontal: 'center' };
        });

        currentRow += reportData.data.length + 2;
      }

      // Save workbook
      const filename = `report-${Date.now()}.xlsx`;
      const filepath = path.join(this.reportsDir, filename);
      await workbook.xlsx.writeFile(filepath);

      return filepath;
    } catch (error) {
      logger.error('Excel generation error:', error);
      throw error;
    }
  }

  // Format value for display
  formatValue(value) {
    if (value === null || value === undefined) {
      return '-';
    }
    if (typeof value === 'number') {
      return value.toLocaleString();
    }
    if (value instanceof Date) {
      return value.toLocaleDateString();
    }
    return String(value);
  }

  // Generate sales report
  async generateSalesReport(data, options) {
    const reportData = {
      summary: {
        totalRevenue: data.reduce((sum, d) => sum + d.revenue, 0),
        totalOrders: data.length,
        averageOrderValue: data.length ? data.reduce((sum, d) => sum + d.revenue, 0) / data.length : 0
      },
      data: data.map(d => ({
        date: d.date,
        orders: d.orders,
        revenue: d.revenue,
        paymentMethod: d.paymentMethod
      }))
    };

    if (options.format === 'pdf') {
      return this.generatePDF(reportData, {
        title: 'Sales Report',
        ...options,
        columns: [
          { header: 'Date', key: 'date' },
          { header: 'Orders', key: 'orders' },
          { header: 'Revenue', key: 'revenue' },
          { header: 'Payment', key: 'paymentMethod' }
        ]
      });
    } else {
      return this.generateExcel(reportData, {
        title: 'Sales Report',
        sheetName: 'Sales',
        ...options
      });
    }
  }

  // Generate inventory report
  async generateInventoryReport(products, options) {
    const reportData = {
      summary: {
        totalProducts: products.length,
        totalValue: products.reduce((sum, p) => sum + (p.price * p.stock), 0),
        lowStockCount: products.filter(p => p.stock <= p.lowStockAlert).length
      },
      data: products.map(p => ({
        name: p.name,
        category: p.category,
        price: p.price,
        stock: p.stock,
        lowStockAlert: p.lowStockAlert,
        value: p.price * p.stock
      }))
    };

    if (options.format === 'pdf') {
      return this.generatePDF(reportData, {
        title: 'Inventory Report',
        ...options
      });
    } else {
      return this.generateExcel(reportData, {
        title: 'Inventory Report',
        sheetName: 'Inventory',
        ...options
      });
    }
  }
}

module.exports = new ReportGenerator();